import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, padding: 15 },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { marginBottom: 20, alignItems: 'center' },
  title: { fontSize: 24, fontWeight: 'bold', color: 'white' },
  subtitle: { fontSize: 16, color: '#FFD700', marginTop: 5, fontWeight: '600' },
  listContainer: { paddingBottom: 30 },
  card: {
    flexDirection: 'row',
    backgroundColor: '#1E293B',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  cardEquipped: { borderColor: '#10B981', backgroundColor: '#064E3B' },
  imageContainer: {
    width: 80,
    height: 80,
    backgroundColor: '#0F172A',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  petImage: { width: 60, height: 60 },
  infoContainer: { flex: 1, justifyContent: 'space-between' },
  petName: { fontSize: 18, fontWeight: 'bold', color: 'white' },
  petDescription: { fontSize: 12, color: '#94A3B8', marginTop: 4, marginBottom: 8 },
  priceText: { fontSize: 14, color: '#FFD700', fontWeight: 'bold', marginBottom: 5 },
  actionContainer: { alignItems: 'flex-start' },
  btn: { paddingVertical: 8, paddingHorizontal: 15, borderRadius: 8 },
  btnBuy: { backgroundColor: '#3B82F6' },
  btnEquip: { backgroundColor: '#F59E0B' },
  btnEquipped: { backgroundColor: '#10B981' },
  btnDisabled: { backgroundColor: '#475569', opacity: 0.7 },
  btnText: { color: 'white', fontWeight: 'bold', fontSize: 14 },
});