import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    chartContainer: {
        marginBottom: 16,
    },
    chartTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 4,
    },
    chartSubtitle: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
        marginBottom: 16,
    },
    cardContainer: {
        backgroundColor: 'rgba(255,255,255,0.08)',
        borderRadius: 12,
        padding: 20,
        alignItems: 'center',
        marginBottom: 16,
    },
    cardTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 12,
    },
    cardContent: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: 8,
    },
    cardValue: {
        color: '#FF6500',
        fontSize: 32,
        fontWeight: 'bold',
        marginRight: 4,
    },
    cardUnit: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 16,
    },
    cardDescription: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 12,
        textAlign: 'center',
    },
    noDataContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
        backgroundColor: 'rgba(75, 159, 225, 0.1)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(75, 159, 225, 0.3)',
        margin: 20,
    },
    noDataContainerSleep: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
        backgroundColor: 'rgba(139, 92, 246, 0.1)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(139, 92, 246, 0.3)',
        margin: 20,
    },
    noDataContainerBreaks: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.3)',
        margin: 20,
    },
    noDataTitle: {
        color: '#4B9FE1',
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 12,
    },
    noDataSubtitle: {
        color: 'rgba(255,255,255,0.8)',
        fontSize: 16,
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 16,
    },
    noDataTip: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
        textAlign: 'center',
        fontStyle: 'italic',
        backgroundColor: 'rgba(75, 159, 225, 0.2)',
        padding: 12,
        borderRadius: 8,
    },
    noDataText: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
        fontStyle: 'italic',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    loadingText: {
        color: 'rgba(255,255,255,0.6)',
        fontSize: 14,
        fontStyle: 'italic',
    },
});